name: Build

on: [push]

env:
  TOOLCHAIN: cruel
  INSTALLER: yes

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        model: [ "G977N" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: sudo apt-get install -y -qq libtinfo5 ccache

      - name: Prepare ccache
        run: |
          ccache -o compression=false -o cache_dir=$HOME/.ccache
          echo "FULL_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "MONTH_DATE=$(date +'%Y-%m')" >> $GITHUB_OUTPUT
        id: ccache_setup

      - name: Kernel Configure
        run: |
          set -e -o pipefail
          ./cruelbuild config                    \
                       model=${{ matrix.model }} \
                       name="Cruel-Final"        \
                       toolchain=$TOOLCHAIN      \
                       +magisk                   \
                       +nohardening              \
                       +ttl                      \
                       +wireguard                \
                       +force_dex_wqhd           \
          2>&1 | tee config.info

      - name: Deploy Toolchain
        run: git clone --depth 1 -j $(nproc) --branch $TOOLCHAIN --single-branch https://github.com/CruelKernel/samsung-exynos9820-toolchain toolchain

      - name: Kernel Build
        run: |
          # This 'fakes' the magisk update script so it always reports success
          mkdir -p usr/magisk
          echo "#!/bin/bash" > usr/magisk/update_magisk.sh
          echo "exit 0" >> usr/magisk/update_magisk.sh
          chmod +x usr/magisk/update_magisk.sh
          
          # Now run the build
          ./cruelbuild :build


      - name: Install mkbootimg tools
        run: |
          wget -q https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/refs/heads/master.tar.gz -O - | tar xzf - mkbootimg.py gki
          chmod +x mkbootimg.py
          sudo mv mkbootimg.py /usr/local/bin/mkbootimg
          sudo mv gki $(python -c 'import site; print(site.getsitepackages()[0])')

      - name: Create Installer
        run: |
          ./cruelbuild :mkimg
          ./cruelbuild :pack

      - name: Upload Final Kernel
        uses: actions/upload-artifact@v4
        with:
          name: CruelKernel-G977N-Success
          path: CruelKernel.zip
